### ISSUE TITLE
functools.cache is only available on python 3.9

### ISSUE THREAD

**Issue by kurtbrose** [percy/percy-selenium-python#13]
meta-data in setup.py says compatible with python 3.6, 3.7, 3.8, 3.9

however, you added a dependency on functools.cache here: https://github.com/percy/percy-selenium-python/commit/2934f121cc63ae039052405a0a2b7c15cec9412d 

this makes import break in anything before python 3.9

recommend either:

1- update meta-data to accurately say compatible only with 3.9+

2- use functools.lru_cache (this is probably better anyway because .cache is unbounded)

also, you might want to consider adding tox to your CI https://tox.readthedocs.io/en/latest/ so build are validated against multiple versions of python

**Comment by rtpg** [comment]
Hit the same issue, `lru_cach(size=None)` gets the same behavior IIRC.

**Comment by wwilsman** [comment]
Hey @kurtbrose and @rtpg! Thanks for opening the issue!

I'll have a PR open soon and a new release to fix this :+1:

**Comment by wwilsman** [comment]
[Released v1.0.2](https://pypi.org/project/percy-selenium/1.0.2/)
