### ISSUE TITLE
percySnapshot(browser=...) changed to percySnapshot(driver=...)

### ISSUE THREAD

**Issue by kurtbrose** [percy/percy-selenium-python#15]
just a heads up -- not a big deal but we stubbed our toe

`percySnapshot` I guess is being kept for backwards compatibility

you might want to also have a signature transformation

```python
def percySnapshot(browser, *a, **kw):
     return percy_snapshot(driver=browser, *a, **kw)
```

or not... we just went straight to `percy_snapshot(driver=...)` but might save someone else from hitting this if they are passing browser as a kwarg

**Comment by kurtbrose** [comment]
also, bravo on the fast fix on `functools.cache` import error yesterday!

we were all really impressed, were not expecting you to be so on-the-ball :-)

**Comment by wwilsman** [comment]
@kurtbrose great idea! I think I may have missed/forgot that the old arg was `browser`. We'll have that fixed shortly :+1:
