### ISSUE TITLE
Migration process from the deprecated "percy" python package is not clear

### ISSUE THREAD

**Issue by maxmalysh** [percy/percy-selenium-python#41]
I decided to migrate from the deprecated package (`percy=2.0.2`):
https://github.com/percy/python-percy-client

I installed `percy-selenium~=1.1.0`.

First of all, it's not clear if the "percy" command should be installed by this package:
```
 % percy config:migrate 
zsh: command not found: percy
```
Second, it will be nice to have some explanations in docs on how to migrate from the older Python SDK. 

For example, I would like to know how we can initialize and finalize builds inside our Django tests:

```
    def test_regression(self):
        root_static_dir = os.path.join(BASE_DIR, 'frontend/static/v2')
        loader = percy.ResourceLoader(
            root_dir=root_static_dir,
            base_url='/static/v2',
            webdriver=self.driver,
        )
        percy_config = percy.Config(default_widths=[1280, 320])

        self.percy_runner = percy.Runner(loader=loader, config=percy_config)
        self.percy_runner.initialize_build()

        for url in self.urls:
            self.driver.get(self.live_server_url + url)
            time.sleep(1)
            percy_snapshot(driver=self.driver, name=name, widths=[1280, 320])

        self.percy_runner.finalize_build()
```
I don't see something similar to the older APIs: `percy.ResourceLoader`, `.initialize_build()` and `.finalize_build()`.

**Comment by ninadbstack** [comment]
@maxmalysh You can follow https://docs.percy.io/docs/migrating-to-percy-cli#non-js-sdk-migration [ Non JS SDK migration section ]. 
Basically remove `@percy/agent`, install cli, and update the package. 
+ there is good amount of differences in how older package worked and how cli based package works. [ i.e. older apis are not present ]. You can check the https://docs.percy.io/docs/python-selenium guide for using newer package with cli.

Note: `percy` command is part of the `@percy/cli` node package and not any of the SDKs.

If you have any further issues while migrating, feel free to [contact support](https://www.browserstack.com/contact#technical-support) and we would look into it.
