### ISSUE TITLE
ImportError: cannot import name 'percySnapshot' from 'percy'

### ISSUE THREAD

**Issue by EnricoSemrau** [percy/percy-selenium-python#5]
Hey,

after following the steps to setup, I get the following error when trying to run the test:
ImportError: cannot import name 'percySnapshot' from 'percy' (/Users/***/PycharmProjects/test3/lib/python3.7/site-packages/percy/__init__.py)

Tried to run it with command:
npx percy exec -- python mytest.py

Any idea how to solve it?
Thanks for your help.

**Comment by Robdel12** [comment]
Hey @EnricoSemrau, thanks for the repot! Which version of Python are you using? And just to be 100% sure, you installed the Percy python package without errors (`pip install percy-python-selenium`) (it seems like it, but want to be sure)

**Comment by EnricoSemrau** [comment]
@Robdel12 Thanks for your reply.
#python --version => Python 3.7.3
I installed the package with "pip3 install percy-python-selenium"
and there was no error

I now tried to clone this repo and run the test as mentioned and it worked fine - but not in my repo when following the readme.

**Comment by Robdel12** [comment]
Good to know! Does the example app work for you? https://github.com/percy/example-percy-python-selenium

**Comment by Robdel12** [comment]
Also curious about using `pip3` to install but not `python3` to invoke the tests. Is it possible the context is getting messed up? My understanding is `pip` will run within the current context of Python (2 or 3), but `pip3` will _always_ be executed in Python 3. 

Curious what could be happening for it to be missing. 🤔

**Comment by EnricoSemrau** [comment]
Thank you, maybe the context is really messed up right now.
Will give it a try and do a fresh clone. Will let u know how it goes.

**Comment by elaa0505** [comment]
from percy.snapshot import percySnapshot
